### ISSUE TITLE
adapting to v5 envs from ale_py

### ISSUE THREAD

**Issue by Howuhh** [floringogianu/atari-agents#6]
Hi! I'm not too familiar with atari protols/versions, but for my purposes I'd like to collect expert data on the latest version of ale_py (e.g. v5 version at https://ale.farama.org/environments/amidar/#variants). Is it possible to adapt checkpoints to this environment version currently without retraining?

**Comment by floringogianu** [comment]
Hi, the `modern` [protocol](https://github.com/floringogianu/atari-agents?tab=readme-ov-file#available-agents) should be identical to v5 (4 frames skipping and sticky actions), I actually believe no retraining is required.

If farama is doing the downsampling in the same way as we're [doing it](https://github.com/floringogianu/atari-agents/blob/main/ale_env.py#L119-L123), it should be fine.

You can see the full `modern` spec here: https://github.com/floringogianu/atari-agents/blob/main/ale_env.py#L47-L60
